
import styled from 'styled-components';
import { BREAKPOINTS } from '../constant';
import Header from './header';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Paragraph } from '../components/Paragraph/Paragraph';
import { Heading } from '../components/Heading/Heading';
import MyImpossibleList from '../components/MyImpossibleList/MyImpossibleList';



export default function Goals() {
    return(
        <>
            <div className={styles.container}>
                <Head>
                    <title>My Goals - NaveenSingh</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <Header/>
                    <Wrapper>
                        <OuterWrapper>
                            <Heading>My Goals</Heading>
                            <hr/> 
                            <span style={{ color:'black',fontSize: '12px',letterSpacing: '0.7px',fontWeight: 'bold', fontStyle: 'italic' }}> Last Updated : 07 Jan, 2022</span>
                            <br/><br/>
                            <Paragraph>
                                On this is goal page where i use to set my goals and check my goal list on weekly base, Whether i achieved or not, Remainder to myself 
                            </Paragraph>
                                <h4 style={{ letterSpacing: '1.2px' }}>Week Goals-(07 Jan - 14 Jan)</h4> <br/>
                                    <MyImpossibleList title="Make Better Plans"/>
                                    <MyImpossibleList title="Make Reading Habit"/>
                                    <MyImpossibleList title="Go to GYM 5 days"/>
                                    <MyImpossibleList title="Code 5 days"/> 
                                    <MyImpossibleList title="No Outside Food For Week"/>
                                {/* <br/>
                                <h4 style={{ letterSpacing: '1.2px' }}>Month Goals</h4> <br/>
                                <MyImpossibleList title="Publish one Technical Blog"/>
                                <MyImpossibleList title="Publish Non Technical Blog"/>
                                <MyImpossibleList title="Finish Current Reading Book"/>
                                <MyImpossibleList title="No Incomplete on PSweb on Website"/> */}
                        </OuterWrapper>
                    </Wrapper>
                </main>
                <br/>
                {/* <Footer/> */}
            </div>
        </>
    );

}


const OuterWrapper = styled.div`
width: 100%;
//min-height: 100vh;
padding-left: 25%;
padding-right: 20%;
box-sizing: border-box;
overflow: hidden;
`;

const Wrapper = styled.div`
  margin-top: 3rem;
  display: flex;
  flex-direction: column;
  gap: 22px;
  @media ${BREAKPOINTS.sm} {
    font-size: 0.7rem;
    margin-bottom: 1.5rem;
  }
`