
import styled from 'styled-components';
import { BREAKPOINTS } from '../constant';
import Header from './header';
import Footer from './footer'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import ThingsIUse from '../components/thingsuse';
import RightNow from './rightnow';
import { Paragraph } from '../components/Paragraph/Paragraph';
import Icon from 'react-icons-kit';
import {androidArrowForward} from 'react-icons-kit/ionicons/androidArrowForward'
import Link from 'next/link';
import {circleRight} from 'react-icons-kit/icomoon/circleRight'

import { Emoji, EmojiStyle } from 'emoji-picker-react';
import { Heading } from '../components/Heading/Heading';


export default function ImpossiblieList() {
    return(
        <>
            <div className={styles.container}>
                <Head>
                    <title>Impossible List - NaveenSingh</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <Header/>
                    <Wrapper>
                        <OuterWrapper>
                            <Heading>Impossible List</Heading>
                            <hr/> 
                            <span style={{ color:'black',fontSize: '12px',letterSpacing: '0.7px',fontWeight: 'bold', fontStyle: 'italic' }}> Last Updated : 26 October, 2022</span>
                            <br/><br/>
                            <Paragraph>
                                This impossible list which i came across from the blog of 
                                <Link href='https://vyshnav.xyz/impossible-list' style={{ fontStyle: 'normal',color: '#3121ed'}} rel="noopener noreferrer">
                                        <span className={styles.thingiuselink}> 
                                            <a href='https://vyshnav.xyz/impossible-list'> vyshnav.xyz </a>
                                        </span> 
                                </Link>
                                Which it looks like quite interesting, After reading had an thought why don&apos;t we have a try, It helps me to push myself to achieve those things
                            </Paragraph>
                            <h4>Life Goals</h4> <br/>

                            <div style={{ color: '#3121ed',fontWeight: 'bold' }}>
                                <Icon size={22} icon={circleRight} /> 
                                <span style={{ color:'black',fontSize: '16px',letterSpacing: '0.7px',fontWeight: 'bold'  }}> 
                                    Read 10 Books in 2023
                                </span>
                            </div>
                            <div style={{ color: '#3121ed',fontWeight: 'bold',marginTop: '0.9rem' }}>
                                <Icon size={22} icon={androidArrowForward} /> 
                                <span style={{ color:'black',fontSize: '16px',letterSpacing: '0.7px',fontWeight: 'bold'  }}> 
                                    Buy PS5 Console 
                                </span>
                            </div>

                            <div style={{ color: '#3121ed',fontWeight: 'bold',marginTop: '0.9rem' }}>
                                <Icon size={22} icon={androidArrowForward} /> 
                                <span style={{ color:'black',fontSize: '16px',letterSpacing: '0.7px',fontWeight: 'bold'  }}> 
                                    Buy Macbook 
                                </span>
                            </div>
                            
                            
                        </OuterWrapper>
                    </Wrapper>
                </main>
                <Footer/>
            </div>
        </>
    );

}


const OuterWrapper = styled.div`
width: 100%;
//min-height: 100vh;
padding-left: 25%;
padding-right: 20%;
box-sizing: border-box;
overflow: hidden;
`;

const Wrapper = styled.div`
  margin-top: 3rem;
  display: flex;
  flex-direction: column;
  gap: 22px;
  @media ${BREAKPOINTS.sm} {
    font-size: 0.7rem;
    margin-bottom: 1.5rem;
  }
`