
import styled from 'styled-components';
import { BREAKPOINTS } from '../constant';
import Header from './header';
import Footer from './footer'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import ThingsIUse from '../components/thingsuse';
import RightNow from './rightnow';
import { Paragraph } from '../components/Paragraph/Paragraph';
import Icon from 'react-icons-kit';
import {androidArrowForward} from 'react-icons-kit/ionicons/androidArrowForward'
import Link from 'next/link';
import {circleRight} from 'react-icons-kit/icomoon/circleRight'

import { Emoji, EmojiStyle } from 'emoji-picker-react';
import { Heading } from '../components/Heading/Heading';
import {angleDoubleRight} from 'react-icons-kit/fa/angleDoubleRight'

import MyImpossibleList from '../components/MyImpossibleList/MyImpossibleList';




export default function ImpossiblieList() {
    return(
        <>
            <div className={styles.container}>
                <Head>
                    <title>Impossible List - NaveenSingh</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <Header/>
                    <Wrapper>
                        <OuterWrapper>
                            <Heading>Impossible List</Heading>
                            <hr/> 
                            <span style={{ color:'black',fontSize: '12px',letterSpacing: '0.7px',fontWeight: 'bold', fontStyle: 'italic' }}> Last Updated : 30 November, 2022</span>
                            <br/><br/>
                            <Paragraph>
                                This impossible list which i came across from the blog of 
                                <Link href='https://vyshnav.xyz/impossible-list' style={{ fontStyle: 'normal',color: '#3121ed'}} rel="noopener noreferrer">
                                        <span className={styles.thingiuselink}> 
                                            <a href='https://vyshnav.xyz/impossible-list'> vyshnav.xyz </a>
                                        </span> 
                                </Link>
                                Which it looks like quite interesting, After reading had an thought why don&apos;t we have a try, It helps me to push myself to achieve those things, 
                            </Paragraph>
                                <h4 style={{ letterSpacing: '1.2px' }}>Life Goals</h4> <br/>
                                    <MyImpossibleList title="Read 10 Books in 2023"/> 
                                    <MyImpossibleList title="Make Passive Income"/>
                                <br/>
                                <h4 style={{ letterSpacing: '1.2px' }}>Habit Goals</h4> <br/>
                                    <MyImpossibleList title="Do Morning Workout 30 days in a row"/>
                                <br/>
                                 <h4 style={{ letterSpacing: '1.2px' }}>Professional</h4> <br/>
                                    <MyImpossibleList 
                                    title="Have one Personal Blog Website"
                                    isdone = "true"
                                    achievedDate= "Oct 26th, 2022"
                                />
                                    <MyImpossibleList title="Become Expert in one technology"/>
                                    <MyImpossibleList title="Publish One Plugin or Theme"/>
                                    <MyImpossibleList title="Publish one app in playstore"/>
                                    <MyImpossibleList title="Contribute to Open Source "/>
                                    <MyImpossibleList title="Gain 500 Twitter Follower"/>
                                    <MyImpossibleList title="One Side Project"/>
                                 <br/>
                                 <h4 style={{ letterSpacing: '1.2px' }}>Creative Goals</h4> <br/>
                                    <MyImpossibleList title="Learn Rive"/>
                                    <MyImpossibleList title="Learn Blender"/>
                                <br/>
                                 <h4 style={{ letterSpacing: '1.2px' }}>Travel Goals</h4> <br/>
                                    <MyImpossibleList title="International Trip"/>
                                    <MyImpossibleList title="Devotional Trip"/>
                                    <MyImpossibleList title="Visit Bali"/>
                                    <MyImpossibleList title="Take a Good Picture for Instagram"/>
                                 <br/>
                                 <h4 style={{ letterSpacing: '1.2px' }}>Fitness Goals</h4> <br/>
                                    <MyImpossibleList title="100 KG in BenchPress"/>
                                    <MyImpossibleList title="100 Push ups on Single Set"/>
                                    <MyImpossibleList title="50 Pull ups on Single Set"/>
                                    <MyImpossibleList title="Bring Ball Shape in Biceps"/>
                                    <MyImpossibleList title="Make an Flat Stomach "/>
                                 <br/>
                                 <h4 style={{ letterSpacing: '1.2px' }}>Personal</h4> 
                                 <MyImpossibleList 
                                    title="Buy PS5 Console"
                                    isdone = "false"
                                    achievedDate= "Oct 22, 2022"
                                    links = "/ps5"
                                />
                                <MyImpossibleList title="Buy Macbook"/>
                                <MyImpossibleList title="Buy Apple Watch"/>
                                <MyImpossibleList title="New Big Car - Honda City "/>
                                <br/>
                        </OuterWrapper>
                    </Wrapper>
                </main>
                <br/>
                {/* <Footer/> */}
            </div>
        </>
    );

}


const OuterWrapper = styled.div`
width: 100%;
//min-height: 100vh;
padding-left: 25%;
padding-right: 20%;
box-sizing: border-box;
overflow: hidden;
`;

const Wrapper = styled.div`
  margin-top: 3rem;
  display: flex;
  flex-direction: column;
  gap: 22px;
  @media ${BREAKPOINTS.sm} {
    font-size: 0.7rem;
    margin-bottom: 1.5rem;
  }
`