import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from './footer'
import Header from './header'
import MainContent from './maincontent'



export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>NaveenSingh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <MainContent/>
      </main>
      <Footer/>
      {/* <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          NaveenSingh
        </a>
      </footer> */}
    </div>
  )
}
