
import styled from 'styled-components';
import { BREAKPOINTS } from '../constant';
import Header from './header';
import Footer from './footer'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ThingsIUse from '../components/thingsuse';
import RightNow from './rightnow';



export default function Now() {
    return(
        <>
            <div className={styles.container}>
                <Head>
                    <title>Uses</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <Header/>
                    <Wrapper>
                        <OuterWrapper>
                            <h3>Now</h3>
                            <RightNow 
                                title="Learning Blender & UI/UX Design"
                                links="https://google.com"
                                emoji=""
                            >

                            </RightNow>
                            {/* <ThingsIUse
                            title="Building this website"
                            titlevalue=""
                            links="">
                            </ThingsIUse> */}
                        </OuterWrapper>
                    </Wrapper>
                </main>
                <Footer/>
            </div>
        </>
    );

}


const OuterWrapper = styled.div`
width: 100%;
//min-height: 100vh;
padding-left: 25%;
padding-right: 20%;
box-sizing: border-box;
overflow: hidden;
`;

const Wrapper = styled.div`
  margin-top: 3rem;
  display: flex;
  flex-direction: column;
  gap: 22px;
  @media ${BREAKPOINTS.sm} {
    font-size: 0.7rem;
    margin-bottom: 1.5rem;
  }
`