
import styled from 'styled-components';
import { BREAKPOINTS } from '../constant';
import Header from './header';
import Footer from './footer'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import ThingsIUse from '../components/thingsuse';
import RightNow from './rightnow';
import { Paragraph } from '../components/Paragraph/Paragraph';
import Icon from 'react-icons-kit';
import {androidArrowForward} from 'react-icons-kit/ionicons/androidArrowForward'
import Link from 'next/link';
import {circleRight} from 'react-icons-kit/icomoon/circleRight'

import { Emoji, EmojiStyle } from 'emoji-picker-react';
import { Heading } from '../components/Heading/Heading';
import {angleDoubleRight} from 'react-icons-kit/fa/angleDoubleRight'


import Image from 'next/image'



export default function Ps5() {
    return(
        <>
            <div className={styles.container}>
                <Head>
                    <title>PS5 - NaveenSingh</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <Header/>
                    <Wrapper>
                        <OuterWrapper>
                            <Heading>PlayStation 5 Console</Heading>
                            <hr/> 
                            <br/>
                            <div style={{width: '540px', height: '720px', position: 'relative', display: 'block',marginLeft: 'auto',marginRight: 'auto' }}>
                                <Image src="/assets/images/test11.png"
                                alt="PS5 Console"
                                layout='fill'/>
                               
                            </div>
                            <div style={{color: 'blue',display: 'flex', justifyContent: 'center',marginTop: '20px'}}>
                                game : horizon forbidden west
                            </div>
                        </OuterWrapper>
                    </Wrapper>
                </main>
                <br/>
            </div>
        </>
    );

}


const OuterWrapper = styled.div`
width: 100%;
//min-height: 100vh;
padding-left: 25%;
padding-right: 20%;
box-sizing: border-box;
overflow: hidden;
`;

const Wrapper = styled.div`
  margin-top: 3rem;
  display: flex;
  flex-direction: column;
  gap: 22px;
  @media ${BREAKPOINTS.sm} {
    font-size: 0.7rem;
    margin-bottom: 1.5rem;
  }
`