
import styled from 'styled-components';
import { BREAKPOINTS } from '../constant';
import Header from './header';
import Footer from './footer'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ThingsIUse from '../components/thingsuse';



export default function Uses() {
    return(
        <>
            <div className={styles.container}>
                <Head>
                    <title>Uses</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <Header/>
                    <OuterWrapper>
                    <h1>Things I Use</h1>
                    </OuterWrapper>
                    <Wrapper>
                        <ThingsIUse
                            title="Editor "
                            titlevalue="VS Code"
                            links="https://code.visualstudio.com/">
                        </ThingsIUse>
                        <ThingsIUse
                            title="Color Theme (personal) "
                            titlevalue="Palenight (Mild Contrast)"
                            links="https://code.visualstudio.com/">
                        </ThingsIUse>
                        <ThingsIUse
                            title="Coding Font (on this website) "
                            titlevalue="MonoLisa"
                            links="https://code.visualstudio.com/">
                        </ThingsIUse>
                        <ThingsIUse
                            title="Coding Font (personal) "
                            titlevalue="Operator Mono"
                            links="https://code.visualstudio.com/">
                        </ThingsIUse>
                    </Wrapper>
                </main>
                <Footer/>
            </div>
        </>
    );

}

const OuterWrapper = styled.div`
width: 100%;
margin-top: 2rem;
//min-height: 100vh;
padding-left: 25%;
padding-right: 20%;
box-sizing: border-box;
overflow: hidden;
`;

const Wrapper = styled.div`
  margin-top: 3rem;
  display: flex;
  flex-direction: column;
  gap: 22px;
  @media ${BREAKPOINTS.sm} {
    font-size: 0.7rem;
    margin-bottom: 1.5rem;
  }
`