
import styled from 'styled-components';
import { BREAKPOINTS } from '../constant';
import Icon from 'react-icons-kit';
import {twitter} from 'react-icons-kit/icomoon/twitter'
import {github} from 'react-icons-kit/icomoon/github'
import {linkedin} from 'react-icons-kit/icomoon/linkedin'
import Header from './header';
import Footer from './footer'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {ic_arrow_right_alt_outline} from 'react-icons-kit/md/ic_arrow_right_alt_outline'

export default function Uses() {
    return(
        <>
            
            <div className={styles.container}>
                <Head>
                    <title>Uses</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <Header/>
                    <Wrapper>
                        <OuterWrapper>
                            <h2>Things I use</h2>
                            <div style={{ color: '#F4A261' }}>
                                <Icon size={64} icon={ic_arrow_right_alt_outline} />
                            </div>
                        </OuterWrapper>
                    </Wrapper>
                </main>
                <Footer/>
                {/* <footer className={styles.footer}>
                    <a
                    href="#"
                    target="_blank"
                    rel="noopener noreferrer"
                    >
                    NaveenSingh
                    </a>
                </footer> */}
            </div>
        </>
    );

}

const OuterWrapper = styled.div`
width: 100%;
//min-height: 100vh;
padding-left: 25%;
padding-right: 20%;
box-sizing: border-box;
overflow: hidden;
`;

const Wrapper = styled.div`
  margin-top: 3rem;
  @media ${BREAKPOINTS.sm} {
    font-size: 0.7rem;
    margin-bottom: 1.5rem;
  }
`